[package]
name = "aztec_dark_market"
type = "contract"
version = "0.1.0"
authors = ["rudazy"]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.50.0", directory="noir-projects/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.50.0", directory="noir-projects/aztec-nr/authwit" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.50.0", directory="noir-projects/aztec-nr/compressed-string" }